services:
  metrics-server:
    image: python:3.11-slim
    working_dir: /app
    volumes:
      - ./:/app
    command: bash -c "apt-get update && apt-get install -y git && pip install -e . && python agent/core/metrics_server.py"
    ports:
      - "8002:8002"

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    depends_on:
      - metrics-server
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:latest
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
    ports:
      - "3000:3000"
